---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - develop
    paths:
      - .github/labels.yml

concurrency:
  group: labels
  cancel-in-progress: true

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
